ProductSubTag:
    type: object
    properties:
        id:
            type: number
            example: 142
        name:
            type: string
            example: '빨간색'
        amount:
            type: number
            example: 1
