ProductMainTag:
    type: object
    properties:
        id:
            type: number
            exmaple: 23
        name:
            type: string
            example: 'M'
        ProductSubTags:
            type: array
            items:
                $ref: './ProductSubTag.yaml#/ProductSubTag'
            example:
                - id: 123
                  name: '빨간색'
                  amount: 1
                - id: 262
                  name: '다크 그린'
                  amount: 1
                - id: 152
                  name: '진청'
                  amount: 2
                - id: 121
                  name: '분홍색'
                  amount: 0

ProductMainTag_Name:
    type: object
    properties:
        name:
            type: string
            example: 'M'
