/api/product/productList:
  get:
    tags:
      - product
    summary: 상품 리스트
    parameters:
      - name: Authorization
        in: header
        required: true
      - name: query
        in: query
        required: true
        schema:
          type: object
          properties:
            page:
              type: string
              description: 아무것도 주지 않을경우 0으로 처리
    responses:
      200:
        $ref: "./openapi.yaml#/success"
      
      500:
        $ref: "./openapi.yaml#/serverError"

