/api/product/ranking:
  post:
    tags:
      - product
    summary: 상품 리스트
    parameters:
      - name: Authorization
        in: header
        required: true
    responses:
      200:
        $ref: "./openapi.yaml#/success"
      401:
        description: 이메일 중복
        schema:
          properties:
            message:
              type: string
              example: 이미 사용중인 아이디 입니다
      402:
        description: 닉네임 중복
        schema:
          properties:
            message:
              type: string
              example: 이미 사용중인 이메일 입니다!
      500:
        $ref: "./openapi.yaml#/serverError"