/api/product/productList:
  get:
    tags:
      - product
    summary: 상품 리스트
    parameters:
      - name: Authorization
        in: header
        required: true
      - in: query
        name: page
        schema:
          type: integer
        description: 홈화면 페이지 쿼리. 아무것도 지급되지 않을 경우 자동으로 0 처리됩니다
    responses:
      200:
        description: 성공 - productData 배열에 담긴체 100개 전달합니다(아래는 예시용 1개)
        schema:
          properties:
            productData:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  productTitle:
                    type: string
                    example: '[MONSTA X 민혁 착용] 리커버리 슬리퍼'
                  productPrice:
                    type: integer
                    example: 19900
                  likes:
                    type: integer
                    example: 9504
                  comments:
                    type: integer
                    example: 1450
                  
      500:
        $ref: "./openapi.yaml#/serverError"

/api/product/productList:
  get:
    tags:
      - product
    summary: 상품 리스트
    parameters:
      - name: Authorization
        in: header
        required: true
      - in: query
        name: productId
        schema:
          type: integer
        description: 상품 아이디
    responses:
      200:
        description: 성공 - productData 배열에 담긴체 100개 전달합니다(아래는 예시용 1개)
        schema:
          properties:
            productData:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  productTitle:
                    type: string
                    example: '[MONSTA X 민혁 착용] 리커버리 슬리퍼'
                  productPrice:
                    type: integer
                    example: 19900
                  likes:
                    type: integer
                    example: 9504
                  comments:
                    type: integer
                    example: 1450
      401:
        description: 상품 조회 결과가 없는경우(productId 에 해당하는 상품이 존재하지 않습니다)
        schema:
          properties:
            message:
              type: string
              example: 상품 조회 결과가 없습니다       
      500:
        $ref: "./openapi.yaml#/serverError"